// runtimes/testdata/usages/vue-sfc/project/src/checkout/PaymentFooter.vue
<script setup lang="ts">
import { computed } from "vue";
import { GlossaText, useGlossa } from "@klarlabs-studio/glossa/vue";
import { useTypedMessages } from "../glossa/glossa-vue";

const props = defineProps<{ total: number; count: number }>();
const { t } = useGlossa();
const m = useTypedMessages();

const payLabel = computed(() => t("checkout.pay", { amount: props.total }));
const failed = computed(() => m.checkout.paymentFailed({ reason: "card" }));
</script>

<template>
  <footer :aria-label="$t('checkout.footer.label')">
    <p>{{ $t("cart.items", { count }) }}</p>
    <GlossaText id="cart.checkout">Zur Kasse</GlossaText>
    <GlossaText
      id="checkout.terms"
      :values="{ total }"
    />
    <GlossaText :id="'checkout.help'" />
    <glossa-text message="checkout.secure">Sicher bezahlen</glossa-text>
    <button type="submit">{{ payLabel }}</button>
    <p v-if="failed">{{ failed }}</p>
  </footer>
</template>

// runtimes/testdata/usages/react-components/project/src/checkout/PaymentFooter.tsx
import { useMemo } from "react";
import { T, useGlossa } from "@klarlabs-studio/glossa/react";

export function PaymentFooter({ total }: { total: number }) {
  const { t } = useGlossa();
  const label = useMemo(() => t("checkout.pay", { amount: total }), [t, total]);
  const hint = () => t("checkout.hint");

  return (
    <footer title={hint()}>
      <T id="checkout.terms" values={{ total }}>
        Es gelten die AGB.
      </T>
      <T id={"checkout.help"} />
      <button type="submit">{label}</button>
    </footer>
  );
}
